[workspace]
resolver = "1"  # lalrpop breaks with 2, did not investigate
members = [
    "api",
    "compiler",
    "cli",
    "testing",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Mark <mverleg.noreply@gmail.com>"]
homepage = "https://github.com/mverleg/stale"
license = "Apache-2.0"
publish = true

[patch.crates-io]
stale-api = { path = "./api" }
stale-lang = { path = "./compiler" }
