[package]
name = "steel-lang"
description = "Steel (Statically-Typed Embedded Expression Language) is a scripting language that can be embedded in other applications."
publish = true

edition.workspace = true
version.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true

build = "build.rs"

[lib]
name = "steel"
path = "src/lib.rs"

[dependencies]
steel-api = "=0.1.0"

regex = "1.9.3"
itertools = "0.11.0"
time = { version = "0.3.26", features = ["serde"] }
env_logger = "0.10.0"
sha2 = "0.10.7"
lalrpop-util = "0.20.0"
serde = "1.0.171"
serde_json = "1.0.105"

dashmap = "5.5.0"
ahash = "0.8.3"
smartstring = { version = "1.0.1", features = ["serde"] }

[build-dependencies]
lalrpop = "0.20.0"



#TODO @mark: clean up dependencies
