[package]
name = "steel-lang"
description = "Steel (Statically-Typed Embedded Expression Language) is a scripting language that can be embedded in other applications."
publish = true

edition.workspace = true
version.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true

#build = "build.rs"

[lib]
name = "steel"
path = "src/lib.rs"

[dependencies]
steel-api = "=0.1.0"

regex = "1.7.1"
itertools = "0.10.5"
time = { version = "0.3.20", features = ["serde"] }
env_logger = "0.10.0"
sha2 = "0.10.6"
dashmap = "5.4.0"
#TODO @mark: clean up dependencies
