
name: 'Fuzz & performance'

on:
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  checks:
    name: Run test module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test module
        uses: docker/build-push-action@v2
        with:
          file: ./ci/fuzz-perf.Dockerfile
          context: .
          push: false
